title: 2Roca
description: artesanos entusiastas en la combinación del hierro y la madera. fabrica de muebles en hierro y madera.
url: https://2roca.com.ar

facebook:
  publisher: https://www.facebook.com/dosroca

logo: /images/me.jpg
social:
  name: 2Roca
  links: 
    - https://www.facebook.com/dosroca
    - https://www.instagram.com/2_roca

google_site_verification: tOncDcF5ChDTh0IOevnhTgy8cpBzl-bN17qaPxdZgT0
lang: es_AR

plugins:
  - jekyll-seo-tag